apiVersion: v2
name: homepage
description: A Helm chart for Kubernetes
type: application
version: 1.3.0
appVersion: "1.16.0"

dependencies:
- name: common
  version: 0.1.1
  repository: file://../common
