{{- include "common.secret" (list . "this.secret") }}
{{- define "this.secret" }}
type: kubernetes.io/service-account-token
metadata:
  annotations:
    kubernetes.io/service-account.name: glance
{{- end }}